name = "bip-explorer"
compatibility_date = "2024-08-23"

[build]
command = "npm run build"
output = "client/dist"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "production" }