name = "bip-explorer"
compatibility_date = "2024-08-23"

[build]
command = "cd client && npx vite build --config ../vite.production.config.js"
output = "dist"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "production" }