name = "bip-explorer"
compatibility_date = "2024-08-23"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "production" }